Module 3 homework
malovichka/AT_course_python_homework pull request #3
Opened 2024-02-07 16:38 UTC by malovichka

2024-02-11 17:00 UTC, akhmialevskiy requested changes
Some code changes are required

2024-02-11 17:00 UTC, akhmialeuski commented on module_3_OOP/business.py
> +                employee.bonus_to_salary(reward)
There is an error here, since this notation is equivalent to the following `company=reward, reward=5`

2024-02-11 17:00 UTC, akhmialeuski commented on module_3_OOP/business.py
> +        self._pay_employee(employee, 10)
It's considered best practice to avoid using magic numbers or values in your code. Instead, define these values as constants with descriptive names.

2024-02-11 17:00 UTC, akhmialeuski commented on module_3_OOP/business.py
> +        self._pay_employee(employee, 10)
Same applies to other similar numbers.

2024-02-11 17:00 UTC, akhmialeuski commented on module_3_OOP/business.py
> +        :rtype: int
Please keep a consistent style in docstrings and variable descriptions. This can be configured once in the IDE and follow this style. 

PS. It does not concern the task itself, but you should habituate yourself to a good programming style right away :)

2024-02-11 17:00 UTC, akhmialeuski commented on module_3_OOP/business.py
> +    def dismiss_employee(self, employee: "Employee", should_remove=True):
This isn't directly related to the task itself, but I would ask that you use type hinting in functions throughout your code

2024-02-11 17:00 UTC, akhmialeuski commented on module_3_OOP/business.py
> +        if not self.is_bankrupt:
`if ... else`?

2024-02-11 17:00 UTC, akhmialeuski commented on module_3_OOP/business.py
> +        self._pay_employee(employee, 12)
Since `do_tasks` and `write_reports` are very similar, I would add a common function that I wrapped in these functions with the appropriate variables.

2024-02-11 17:00 UTC, akhmialeuski commented on module_3_OOP/business.py
> +                employee.bonus_to_salary(reward)
You can test yourself by changing the value for the `reward` and see the result

2024-02-11 17:00 UTC, akhmialeuski commented on module_3_OOP/business.py
> +            reward = 5
I would move `reward = 5` to a class attribute because it allows for easier management of such values, making the code more readable and simplifying future modifications by having a single point of change that affects all instances of the class.

2024-02-11 17:00 UTC, akhmialeuski commented on module_3_OOP/business.py
> +        if not self.is_bankrupt:
I believe It would be better to do something like this:

```python
class Company:
    # Adding a class attribute for reward
    reward = 5

    def make_a_party(self):
        """Party time! All employees get 5 money"""
        # Checking that the company is not bankrupt before the party starts
        if not self.is_bankrupt:
            for employee in self.employees:
                employee.bonus_to_salary(self.reward)
                self.__money -= self.reward
                # Checking the company's bankruptcy status after each allocation
                if self.__money < 0:  # Or another logic for determining bankruptcy
                    self.go_bankrupt()
                    break  # Exiting the loop if the company goes bankrupt
```

In this code, if the company becomes bankrupt during the distribution of bonuses, the process stops to prevent further financial issues.

2024-02-11 17:00 UTC, akhmialeuski commented on module_3_OOP/business.py
> +        print(self.__money)
Cosmetic: It would be better to display the company name as well

2024-02-11 17:00 UTC, akhmialeuski commented on module_3_OOP/business.py
> +            self.company.notify_im_leaving(self)
I would add an error message if quitting twice in a row.

2024-02-11 17:00 UTC, akhmialeuski commented on module_3_OOP/business.py
> +    bill.join_company(fruits_company)
It looks like an employee may be employed by a bankrupt company

```python
doors_company.go_bankrupt()
bill.join_company(doors_company)
bill.join_company(fruits_company)
```

2024-02-11 17:00 UTC, akhmialeuski commented on module_3_OOP/business.py
> +    def dismiss_employee(self, employee: "Employee", should_remove=True):
I really don't like the use of `should_remove=True` here. I understand why you did it, but it makes the code very coherent and unreadable.

I would ask you to redo it, but don't waste a lot of time. If you don't have any ideas at all, leave it as it is, since this code works.

2024-02-13 08:03 UTC, malovichka commented on module_3_OOP/business.py
> +        if not self.is_bankrupt:
We need to check for bankruptcy two times - before and after giving money, that's why there are two if's.
And if first condition is not satisfied, then the programm will go straight to the second. If using if..else, then we still need second if condition to trigger bankruptcy if money went <=0 during first if..else.

2024-02-13 08:03 UTC, malovichka commented on module_3_OOP/business.py
> +                employee.bonus_to_salary(reward)
Fixed

2024-02-13 08:03 UTC, malovichka commented on module_3_OOP/business.py
> +        self._pay_employee(employee, 10)
Fixed

2024-02-13 08:03 UTC, malovichka commented on module_3_OOP/business.py
> +        :rtype: int
In this particular case docstrings and variable descriptions were provided in the template that was given as a part of homework.
Thanks for the advice, I'll try to follow it.

2024-02-13 08:04 UTC, malovichka commented on module_3_OOP/business.py
> +        self._pay_employee(employee, 12)
fixed, added `submit_work_results` function

2024-02-13 08:04 UTC, malovichka commented on module_3_OOP/business.py
> +            reward = 5
fixed

2024-02-13 08:07 UTC, malovichka commented on module_3_OOP/business.py
> +        print(self.__money)
fixed

2024-02-13 08:11 UTC, malovichka commented on module_3_OOP/business.py
> +            self.company.notify_im_leaving(self)
fixed

2024-02-13 08:16 UTC, malovichka commented on module_3_OOP/business.py
> +        if not self.is_bankrupt:
Discussed in Teams current implementation.

2024-02-13 08:44 UTC, malovichka commented on module_3_OOP/business.py
> +    bill.join_company(fruits_company)
Good point, it was not mentioned in the task but it's quite logical. Fixed.

2024-02-13 08:45 UTC, malovichka commented on module_3_OOP/business.py
> +    def dismiss_employee(self, employee: "Employee", should_remove=True):
added type hinting, implementation not changed

2024-02-13 20:34 UTC, akhmialevskiy approved these changes
looks good

2024-02-15 15:00 UTC, merged